#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
FROM eclipse-temurin:8-jdk-centos7

ENV LANG C.UTF-8

WORKDIR /root
COPY code_run.sh /root/code_run.sh
RUN wget https://dlcdn.apache.org/maven/maven-3/3.8.7/binaries/apache-maven-3.8.7-bin.tar.gz
RUN chmod 755 /root/code_run.sh
RUN tar -xvf /root/apache-maven-3.8.7-bin.tar.gz -C /opt/

RUN yum install unzip curl git -y
RUN yum install -y java-1.8.0-openjdk-devel


COPY APP-META/docker-config/onetest.collector.tar.gz /root/onetest.collector.tar.gz

WORKDIR /root

RUN tar -xvf /root/onetest.collector.tar.gz -C /root/ && \
    rm -rf /root/onetest.collector.tar.gz


WORKDIR /root
CMD ["/bin/bash", "-c", "source code_run.sh"]